platform :ios, '8.0'

use_frameworks!

target "Demo" do
  pod "AFNetworking+streaming", :path => "../"
end

# Uncomment the following lines to add testing dependencies
# target "DemoTests" do
#   pod 'Expecta'
# end
