platform :ios, '7.0'

target "Demo" do
  pod "AFNetworking+streaming", :path => "../"
  pod "AFNetworking", "~> 2.3"
  pod "SBJson", "~> 4"
end

# Uncomment the following lines to add testing dependencies
# target "DemoTests" do
#   pod 'Expecta'
# end
